[general]
live_config_reload = true

[window]
dimensions = { columns = 300, lines = 100 }
position = { x = 0, y = 0 }
padding = { x = 6, y = 6 }

[scrolling]
history = 100000

[font]
normal = { family = "FiraCode Nerd Font" }
size = 14.0
offset = { y = 1 }

[cursor]
style = {shape = "beam", blinking = "off"}

# Colors (One Dark)
# Default colors
[colors.primary]
background = '#282c34'
foreground = '#abb2bf'
# Normal colors
[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'
# Bright colors
[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'
